apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: cv-lab
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
